security:
  secret:
    key: 36c2f22d-74e1-4bb3-892f-a0e2c945f1c3

spring:
  application:
    name: walletapp
  datasource:
    url: jdbc:mysql://localhost:3306/fintechdb?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Wumingwei1983!
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled:
      version: "openapi_3_0"
  swagger-ui:
    enabled: true
    operations-sorter: "method"
    tags-sorter: "alpha"
    display-request-duration: true
    path: /swagger-ui.html

